branch-defaults:
  default:
    environment: marysastrotalks
  master:
    environment: marysastrotalks
environment-defaults:
  marysastrotalks:
    branch: null
    repository: null
  marysastrotalks-dev:
    branch: null
    repository: null
global:
  application_name: maryastrotalks
  default_ec2_keyname: markskey
  default_platform: PHP 5.4
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
